### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by jagdeepmarahar** [Kovah/LinkAce#506] opened 2022-07-10 03:14 UTC
Hi all. I've managed to install linkace on my Synology using docker. I setup 2 factor authentication and saved it. Now I am not able to login as it is not accepting those 2fa codes. I also lost the recovery codes. I have tried reinstalling it after deleting docker-compose file and .env file but it still asking me for 2fa. Can somebody please help me to reset it. TIA.

**Comment by Kovah** [comment] 2022-07-10 19:08
https://www.linkace.org/docs/v1/cli/#view-2fa-recovery-codes

**Comment by jagdeepmarahar** [comment] 2022-07-16 23:22
> https://www.linkace.org/docs/v1/cli/#view-2fa-recovery-codes

I've tried viewing 2-FA codes using the command given in the link above, but getting an error. 
I've attached the screenshot of the error here. Please have a look at it. Thanks.
![Screenshot 2022-06-16 164045](https://user-images.githubusercontent.com/69293047/179374857-d31bc86e-4bf6-4223-b997-aad7f957fcda.png)

**Comment by Kovah** [comment] 2022-07-17 08:15
The problem is you generated a new APP_KEY or changed the old one, then if you try to decrypt the old encrypted data it will show the DecryptException: The MAC is invalid.

So, there is no way to recover the old account with the regular methods. If you have direct access to the database, you might try to remove any values from the `two_factor_secret` and `two_factor_recovery_codes` columns for your user in the `users` table.

**Comment by Kovah** [comment] 2022-10-12 08:44
Closing this for now as all questions are answered. Feel free to re-open if something is unclear.

**Closed by Kovah** 2022-10-12 08:44 UTC
